### ISSUE TITLE
Auth Request Headers

### ISSUE THREAD

**Issue by omr-htp** [cradle77/BlazorSecurityDemo#6]
Hello,
Thank you for this great example.

i have a question please ,
i'm working on a multi tenant app.
i want to send tenant id to identity server during authentication, so the server verifies it and include it in the token (as claim).

can i add a request header to the authentication request  (not every request, just token creation request) 
i tried to add header value to the named client (AddHttpClient("api")) 
the value came to the server with all requests except authentication request.

thank you in advance.

**Comment by cradle77** [comment]
Hello, 

The reason why you don't see that header is because the authentication and authorization requests are done through oidc-client instead of HttpClient.

Apparently the best solution is using its acr_values setting to send the tenant as a querystring paramater, as described here:
https://stackoverflow.com/questions/61972506/pass-custom-http-header-to-identityserver-4-from-oidc-client-js
http://docs.identityserver.io/en/3.1.0/endpoints/authorize.html

On the Blazor side, unfortunately this is not exposed by OidcProviderOptions, so it's a bit tricky to implement.
Here's an example on how to do it:
https://github.com/cradle77/BlazorSecurityDemo/blob/tests/custom-oidc-parameters/BlazorClient/Program.cs

Let me know 👍

**Comment by omr-htp** [comment]
Hello,

Unfortunately i couldn't get acr_values at server.

i tried this with no results
```
public async Task GetProfileDataAsync(ProfileDataRequestContext context)
{
    string acr_values = context?.ValidatedRequest.Raw.Get("acr_values");
}
```

this Issue describes my problem :

https://github.com/IdentityServer/IdentityServer4/issues/2025

Thanks you very much for your great answer.

**Comment by cradle77** [comment]
Hello, 

I don't think that's the correct way to proceed, you shouldn't fetch the acr_values in the profile service.

The way I would do it is:
- Add a `Tenant` property to the `TUser` object (e.g. `ApplicationUser`)
- you can set a value to that property from the Login Controller, for example, when authenticating the user. In order to retrieve the tenant, just do
```
var context = await _interaction.GetAuthorizationContextAsync(model.ReturnUrl);
var tenant = context.Tenant;
```

- Create a custom `IUserClaimsPrincipalFactory` which reads that property from `TUser` and adds it as a claim to the `ClaimsPrincipal`
- Add the new `Tenant` claim to the required claims for the `profile` scope (similarly to what I've done for the `role` claim), so it will be returned with the ID Token
- optionally, add it to the claims for the API Resource, so you will also get it in the access token

HTH :) 

EDIT: I just pushed a change on that branch to demonstrate how to retrieve the tenant during the login phase:
![image](https://user-images.githubusercontent.com/5619949/89733775-bad4c800-da4f-11ea-93ab-e86003bb6e6c.png)

**Comment by omr-htp** [comment]
Hello,

Thank you very much,

yes it's working ,but i can't deppend on a property for TUser. why :
In my app the user may have more than one tenant id, and he can switch the current Tenant Id anytime he want, and the client app sends the new tenant id (in headers) with the refreshtoken request ,
i use UpdateAccessTokenClaimsOnRefresh = true in the Client so the server can check and confirm the new tenant is ok and include the tenent id as a claim in the new token


```
public async Task GetProfileDataAsync(ProfileDataRequestContext context)
{
                ....
                if (_accessor.HttpContext.Request.Headers.TryGetValue("tid", out StringValues tid))
                {
                    var userHasComp = await dbContext.Set<UserComp>()
                        .AnyAsync(u => u.UserId.ToString() == sub && u.CompId.ToString() == tid.ToString());

                    if (userHasComp)
                    {
                        claims.Add(new Claim("tid", tid));
                    }
                }
                .....
}
```
i'm using the same scenario in my desktop client , 

i know it my be not that good idea but it's working.

i'll check again tomorrow and let you know,
again , i have to say thank you very much for your cooperation.
